[features]
seeds = false
[programs.localnet]
post = "9UEB181u3WjjiiWV2WWHHEq16LPhkZa8STAUHXBLx2bp"
comment = "9rbzD7Ae9doWFbxpZw9SYH6Jzw19Gug7heo5i4eHQHE7"
user = "81g9iq98nK574jk5G5tbYy19QZSrdVMfyFjmxj1EqVw5"
block = "5ZGZX4uPcbRmXVhAYmiSs3Bf3h6uBvcph2LPxG2a5Sxv"
message = "7Qy3XGGyGXVZAeC1Thxz38jwQ49jgyMtA2pQgNtB8Z4y"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/aland/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
